import React, { useEffect, useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { motion } from 'framer-motion';
import './ProviderProfileC.css';

// Import data from JSON files
import providersData from "../../data/providers.json";
import productsData from "../../data/products.json";
import servicesData from "../../data/services.json";

const ProviderProfileC = () => {
  const { providerId } = useParams();
  const navigate = useNavigate();
  const [providerData, setProviderData] = useState(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [activeTab, setActiveTab] = useState('products');

  useEffect(() => {
    const fetchProviderData = async () => {
      setLoading(true);
      setError('');
      try {
        console.log('🔍 Fetching provider data for:', providerId);
        
        // First try to find provider in JSON data
        const jsonProvider = findProviderInJson(providerId);
        if (jsonProvider) {
          console.log('✅ Found provider in JSON data:', jsonProvider);
          setProviderData(jsonProvider);
          return;
        }
        
        // If not found in JSON, check localStorage (generated by ServiceProvidersList)
        const allProvidersData = JSON.parse(localStorage.getItem('allProvidersData') || '{}');
        
        console.log('📊 All providers data keys:', Object.keys(allProvidersData));
        
        // Try to find provider by ID
        let provider = allProvidersData[providerId];
        
        if (provider) {
          console.log('✅ Found provider in localStorage:', provider);
          setProviderData(provider);
        } else {
          // Try alternative ID formats
          const alternativeId = Object.keys(allProvidersData).find(key => 
            key.includes(providerId) || providerId.includes(key)
          );
          
          if (alternativeId) {
            console.log('🔄 Found alternative ID:', alternativeId);
            provider = allProvidersData[alternativeId];
            setProviderData(provider);
          } else {
            console.log('❌ Provider not found, generating fallback');
            // Generate fallback provider data
            const fallbackProvider = generateFallbackProvider(providerId);
            setProviderData(fallbackProvider);
            
            // Also store it for future use
            allProvidersData[providerId] = fallbackProvider;
            localStorage.setItem('allProvidersData', JSON.stringify(allProvidersData));
          }
        }

      } catch (err) {
        console.error('❌ Error fetching provider profile', err);
        setError('Failed to load provider profile. Please try again.');
      } finally {
        setLoading(false);
      }
    };

    if (providerId) {
      fetchProviderData();
    } else {
      setError('No provider ID specified');
      setLoading(false);
    }
  }, [providerId]);

  // Find provider in JSON data
  const findProviderInJson = (providerId) => {
    let foundProvider = null;
    
    // Search in providers.json
    if (providersData) {
      if (Array.isArray(providersData)) {
        foundProvider = providersData.find(p => 
          p.id.toString() === providerId || 
          p.id === providerId ||
          p.name?.toLowerCase().includes(providerId.toLowerCase())
        );
      } else if (providersData.providers && Array.isArray(providersData.providers)) {
        foundProvider = providersData.providers.find(p => 
          p.id.toString() === providerId || 
          p.id === providerId ||
          p.name?.toLowerCase().includes(providerId.toLowerCase())
        );
      }
    }

    if (foundProvider) {
      console.log('✅ Found provider in JSON:', foundProvider);
      return enhanceProviderData(foundProvider);
    }

    return null;
  };

  // Enhance provider data with additional fields
  const enhanceProviderData = (provider) => {
    const cities = ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad"];
    const experiences = ["1+ years", "2+ years", "3+ years", "5+ years", "8+ years", "10+ years"];
    const priceRanges = {
      low: "₹500 - ₹2000",
      medium: "₹1000 - ₹5000", 
      high: "₹2000 - ₹10000"
    };

    // Determine price range based on service type
    let priceRange = priceRanges.medium;
    const serviceName = provider.service || provider.category || "";
    
    if (["bridal_makeup", "wedding_gifts", "art_paintings", "corporate_event_decor", "party_wear_outfits"].some(id => 
      serviceName.toLowerCase().includes(id))) {
      priceRange = priceRanges.high;
    } else if (["quick_snacks", "south_indian_meals", "north_indian_meals", "diwali_festival_kit"].some(id => 
      serviceName.toLowerCase().includes(id))) {
      priceRange = priceRanges.low;
    }

    return {
      id: provider.id?.toString() || providerId,
      name: provider.name,
      description: provider.description || `Passionate ${serviceName.toLowerCase()} expert with excellent customer satisfaction.`,
      image: provider.image || provider.imagePath || "/assets/default-profile.png",
      rating: provider.rating || (4.0 + Math.random() * 1).toFixed(1),
      reviews: provider.reviews || Math.floor(Math.random() * 100) + 20,
      location: provider.location || cities[Math.floor(Math.random() * cities.length)],
      experience: provider.experience || experiences[Math.floor(Math.random() * experiences.length)],
      priceRange: provider.priceRange || priceRange,
      services: provider.services || [serviceName, "Custom Designs", "Premium Quality Work"],
      portfolio: provider.portfolio || generatePortfolio(serviceName),
      products: provider.products || getProductsForProvider(provider.id || providerId, serviceName),
      phone: provider.phone || `+91 ${Math.floor(9000000000 + Math.random() * 1000000000)}`,
      email: provider.email || `${provider.name.toLowerCase().replace(' ', '.')}@sheworks.com`,
      bio: provider.bio || `I am a passionate and dedicated ${serviceName.toLowerCase()} specialist with years of experience. I take pride in delivering high-quality work and ensuring complete customer satisfaction.`,
      providerType: provider.providerType || (Math.random() > 0.3 ? 'verified' : 'professional'),
      responseRate: provider.responseRate || "95%",
      completionRate: provider.completionRate || "98%",
      onTimeDelivery: provider.onTimeDelivery || "96%",
      customerSatisfaction: provider.customerSatisfaction || `${(4.0 + Math.random() * 1).toFixed(1)}/5`,
      category: provider.category || serviceName,
      contact: provider.contact || provider.phone
    };
  };

  // Get products for provider from products.json
  const getProductsForProvider = (providerId, serviceName) => {
    let products = [];
    
    // Search in products.json
    if (productsData) {
      if (Array.isArray(productsData)) {
        products = productsData.filter(product => 
          product.providerId === providerId || 
          product.providerId?.toString() === providerId ||
          product.category?.toLowerCase().includes(serviceName.toLowerCase())
        );
      } else if (productsData.products && Array.isArray(productsData.products)) {
        products = productsData.products.filter(product => 
          product.providerId === providerId || 
          product.providerId?.toString() === providerId ||
          product.category?.toLowerCase().includes(serviceName.toLowerCase())
        );
      }
    }

    // If no products found, generate some
    if (products.length === 0) {
      products = generateFallbackProducts(providerId, serviceName);
    }

    return products.slice(0, 10); // Limit to 10 products
  };

  // Generate comprehensive fallback provider
  const generateFallbackProvider = (providerId) => {
    console.log('🛠️ Generating fallback provider for:', providerId);
    
    // Extract service type from provider ID
    const serviceType = providerId.split('_')[0];
    const serviceNames = {
      'hand': 'Hand Embroidery',
      'machine': 'Machine Embroidery', 
      'pearl': 'Pearl Embroidery',
      'beads': 'Beads Embroidery',
      'south': 'South Indian Meals',
      'north': 'North Indian Meals',
      'quick': 'Quick Snacks',
      'handmade': 'Handmade Gifts',
      'birthday': 'Birthday Gifts',
      'wedding': 'Wedding Gifts',
      'anniversary': 'Anniversary Gifts',
      'art': 'Art Paintings',
      'paper': 'Paper Crafting',
      'clay': 'Clay Modelling',
      'collage': 'Collage Making',
      'ladies': 'Ladies Wear Fashion',
      'mens': 'Mens Wear Fashion',
      'kids': 'Kids Wear Fashion',
      'ethnic': 'Ethnic Wear',
      'party': 'Party Wear Outfits',
      'bridal': 'Bridal Makeup',
      'skin': 'Skin Care Routine',
      'hair': 'Hair Care Products',
      'manicure': 'Manicure & Pedicure',
      'full': 'Full Body Massage',
      'cake': 'Cake Artistry',
      'cupcake': 'Cupcake & Muffin Creations',
      'cookies': 'Cookies & Biscuits',
      'bread': 'Bread & Pastry Delight',
      'birthday': 'Birthday Decor',
      'wedding': 'Wedding Decor',
      'festive': 'Festive Home Decor',
      'anniversary': 'Anniversary Decor',
      'corporate': 'Corporate Event Decor',
      'indoor': 'Indoor Plants',
      'plant': 'Plant Starter Kit',
      'herb': 'Herb Garden Kit',
      'vegetable': 'Vegetable Seed Kit',
      'flower': 'Flower Seed Kit',
      'microgreen': 'Microgreen Kit',
      'puja': 'Puja Kits',
      'festival': 'Festival Essentials',
      'holi': 'Holi Festival Kit',
      'diwali': 'Diwali Festival Kit',
      'ganapati': 'Ganapathi Festival Kit',
      'festive': 'Festive Craft Delight',
      'lotus': 'Lotus Puja Decor Kit'
    };

    const serviceName = serviceNames[serviceType] || `${serviceType} Services`;
    
    // Indian women names
    const indianWomenNames = [
      "Priya Sharma", "Ananya Patel", "Divya Reddy", "Sneha Kumar", "Riya Gupta",
      "Neha Singh", "Pooja Mehta", "Kavya Joshi", "Shreya Malhotra", "Aditi Choudhury"
    ];
    
    const name = indianWomenNames[Math.floor(Math.random() * indianWomenNames.length)];
    const cities = ["Mumbai", "Delhi", "Bangalore", "Hyderabad", "Chennai", "Kolkata", "Pune", "Ahmedabad"];
    const experiences = ["2+ years", "3+ years", "5+ years", "8+ years", "10+ years"];

    return {
      id: providerId,
      name: name,
      description: `Professional ${serviceName.toLowerCase()} expert with excellent customer satisfaction and quality work.`,
      image: `/assets/ServiceProviderImages/${serviceType}_embroidery.jpg`.replace('_embroidery', ''),
      rating: (4.0 + Math.random() * 1).toFixed(1),
      reviews: Math.floor(Math.random() * 100) + 20,
      location: cities[Math.floor(Math.random() * cities.length)],
      experience: experiences[Math.floor(Math.random() * experiences.length)],
      priceRange: ['₹500 - ₹2000', '₹1000 - ₹5000', '₹2000 - ₹10000'][Math.floor(Math.random() * 3)],
      providerType: Math.random() > 0.3 ? 'verified' : 'professional',
      products: generateFallbackProducts(providerId, serviceName),
      portfolio: generatePortfolio(providerId, serviceName),
      phone: `+91 ${Math.floor(9000000000 + Math.random() * 1000000000)}`,
      email: `${name.toLowerCase().replace(' ', '.')}@sheworks.com`,
      bio: `I am a passionate and dedicated ${serviceName.toLowerCase()} specialist with years of experience. I take pride in delivering high-quality work and ensuring complete customer satisfaction. My goal is to bring your vision to life with creativity and precision.`,
      responseRate: "95%",
      completionRate: "98%",
      onTimeDelivery: "96%",
      customerSatisfaction: `${(4.0 + Math.random() * 1).toFixed(1)}/5`,
      contact: `+91 ${Math.floor(9000000000 + Math.random() * 1000000000)}`
    };
  };

  // Generate fallback products with realistic data
  const generateFallbackProducts = (providerId, serviceName) => {
    const productTemplates = {
      'embroidery': [
        { name: "Custom Embroidery Design", basePrice: 1200 },
        { name: "Personalized Monogram Service", basePrice: 800 },
        { name: "Traditional Motif Embroidery", basePrice: 1500 },
        { name: "Modern Abstract Embroidery", basePrice: 1300 },
        { name: "Bridal Embroidery Package", basePrice: 5000 },
        { name: "Kids Clothing Embroidery", basePrice: 600 },
        { name: "Home Decor Embroidery", basePrice: 1800 },
        { name: "Accessories Embroidery", basePrice: 900 },
        { name: "Corporate Logo Embroidery", basePrice: 2000 },
        { name: "Special Occasion Embroidery", basePrice: 2500 }
      ],
      'food': [
        { name: "Traditional Meal Package", basePrice: 300 },
        { name: "Special Diet Meal Plan", basePrice: 500 },
        { name: "Festival Special Menu", basePrice: 800 },
        { name: "Healthy Snacks Pack", basePrice: 200 },
        { name: "Custom Thali Service", basePrice: 400 },
        { name: "Party Catering Package", basePrice: 1500 },
        { name: "Dietary Specific Meals", basePrice: 350 },
        { name: "Traditional Sweets Box", basePrice: 600 },
        { name: "Ready-to-Cook Kit", basePrice: 250 },
        { name: "Special Occasion Feast", basePrice: 1200 }
      ],
      'default': [
        { name: "Basic Service Package", basePrice: 1000 },
        { name: "Premium Service Package", basePrice: 2500 },
        { name: "Custom Design Service", basePrice: 1500 },
        { name: "Express Delivery Service", basePrice: 1800 },
        { name: "Standard Service Package", basePrice: 1200 },
        { name: "Luxury Service Package", basePrice: 3500 },
        { name: "Budget Friendly Package", basePrice: 600 },
        { name: "Professional Service", basePrice: 2000 },
        { name: "Quick Service Option", basePrice: 800 },
        { name: "Comprehensive Service", basePrice: 2800 }
      ]
    };

    let template = productTemplates.default;
    if (serviceName.toLowerCase().includes('embroidery')) template = productTemplates.embroidery;
    if (serviceName.toLowerCase().includes('meal') || serviceName.toLowerCase().includes('food')) template = productTemplates.food;

    return template.map((product, index) => ({
      id: `prod_${providerId}_${index}`,
      name: product.name,
      price: Math.floor(product.basePrice * (0.8 + Math.random() * 0.4)), // Variation of ±20%
      description: `High-quality ${serviceName.toLowerCase()} service with excellent results and customer satisfaction.`,
      image: `/assets/ServiceProviderImages/Serviceproviderproductimages/product_${index + 1}.jpg`,
      rating: (Math.random() * 1 + 4).toFixed(1), // 4.0 - 5.0
      reviews: Math.floor(Math.random() * 50),
      inStock: Math.random() > 0.1, // 90% in stock
      type: product.basePrice > 2000 ? 'service' : 'product'
    }));
  };

  // Generate portfolio items
  const generatePortfolio = (providerId, serviceName) => {
    return Array.from({ length: 6 }, (_, index) => ({
      image: `/assets/ServiceProviderImages/portfolio_${index + 1}.jpg`,
      title: `${serviceName} Work ${index + 1}`,
      description: `Beautiful ${serviceName.toLowerCase()} work showcasing quality and craftsmanship.`,
      price: `₹${(800 + index * 400)}`
    }));
  };

  // Calculate average rating from products
  const averageRating = providerData?.products?.length
    ? (providerData.products.reduce((sum, product) => sum + Number(product.rating || 0), 0) / providerData.products.length).toFixed(1)
    : providerData?.rating || '4.5';

  // Get profile image URL with fallback
  const getProfileImage = () => {
    if (!providerData?.image) return '/assets/default-profile.png';
    
    // Handle image path issues
    let imagePath = providerData.image;
    if (!imagePath.startsWith('/assets/')) {
      imagePath = `/assets/ServiceProviderImages/${imagePath}`;
    }
    
    return imagePath;
  };

  // Handle booking
  const handleBooking = () => {
    navigate(`/booking/${providerId}`, { 
      state: { 
        providerName: providerData?.name,
        providerData: providerData
      }
    });
  };

  // Handle chat
  const handleChat = () => {
    navigate(`/client/chat/${providerId}`, {
      state: {
        providerName: providerData?.name,
        providerImage: getProfileImage()
      }
    });
  };

  // Handle review
  const handleReview = () => {
    navigate(`/client/writereview/${providerId}`, {
      state: {
        providerName: providerData?.name,
        providerImage: getProfileImage()
      }
    });
  };

  // Add to favorites
  const handleAddToFavorites = () => {
    const favorites = JSON.parse(localStorage.getItem('clientFavorites') || '[]');
    const favorite = {
      providerId,
      providerName: providerData?.name,
      providerImage: getProfileImage(),
      category: providerData?.category || providerId.split('_')[0],
      rating: averageRating,
      location: providerData?.location,
      addedAt: new Date().toISOString()
    };
    
    const existingIndex = favorites.findIndex(fav => fav.providerId === providerId);
    if (existingIndex === -1) {
      favorites.push(favorite);
      localStorage.setItem('clientFavorites', JSON.stringify(favorites));
      alert('✅ Added to favorites!');
    } else {
      alert('⚠️ Already in favorites!');
    }
  };

  // Quick buy product
  const handleQuickBuy = (product) => {
    if (product.type === 'service') {
      navigate(`/booking/${providerId}`, {
        state: {
          product,
          provider: providerData
        }
      });
    } else {
      navigate(`/client/quick-buy/${providerId}/${product.id}`, {
        state: {
          product,
          provider: providerData
        }
      });
    }
  };

  // Add product to cart
  const handleAddToCart = (product, e) => {
    e?.stopPropagation();
    
    if (product.type === 'service') {
      navigate(`/booking/${providerId}`, {
        state: {
          product,
          provider: providerData
        }
      });
      return;
    }

    const cart = JSON.parse(localStorage.getItem('clientCart') || '[]');
    const cartItem = {
      ...product,
      providerId,
      providerName: providerData?.name,
      quantity: 1,
      addedAt: new Date().toISOString()
    };
    
    const existingItemIndex = cart.findIndex(item => item.id === product.id && item.providerId === providerId);
    if (existingItemIndex > -1) {
      cart[existingItemIndex].quantity += 1;
    } else {
      cart.push(cartItem);
    }
    
    localStorage.setItem('clientCart', JSON.stringify(cart));
    alert(`🛒 ${product.name} added to cart!`);
  };

  // Debug function
  const debugProviderData = () => {
    console.log('🔍 Provider Data Debug:', providerData);
    console.log('📊 localStorage allProvidersData:', JSON.parse(localStorage.getItem('allProvidersData') || '{}'));
    console.log('📁 providersData:', providersData);
    console.log('📦 productsData:', productsData);
  };

  if (loading) {
    return (
      <div className="provider-profile-loading">
        <div className="loading-spinner"></div>
        <p>Loading provider profile...</p>
      </div>
    );
  }

  if (error) {
    return (
      <div className="provider-profile-error">
        <div className="error-content">
          <h2>😔 Unable to Load Profile</h2>
          <p>{error}</p>
          <button 
            onClick={() => window.location.reload()} 
            className="retry-button"
          >
            🔄 Try Again
          </button>
          <button 
            onClick={() => navigate('/client/services')} 
            className="back-button"
          >
            ← Back to Services
          </button>
        </div>
      </div>
    );
  }

  if (!providerData) {
    return (
      <div className="provider-profile-error">
        <div className="error-content">
          <h2>Provider Not Found</h2>
          <p>The service provider you're looking for is not available.</p>
          <button 
            onClick={() => navigate('/client/services')} 
            className="back-button"
          >
            ← Back to Services
          </button>
        </div>
      </div>
    );
  }

  return (
    <motion.div
      className="provider-profile-container"
      initial={{ opacity: 0, y: 30 }}
      animate={{ opacity: 1, y: 0 }}
      transition={{ duration: 0.5 }}
    >
      {/* Debug button - remove in production */}
      <button 
        onClick={debugProviderData}
        className="debug-button"
      >
        🐛 Debug
      </button>

      {/* Header Section */}
      <div className="profile-header">
        <div className="header-content">
          <button 
            onClick={() => navigate(-1)} 
            className="back-nav-button"
          >
            ← Back to Services
          </button>
        </div>
      </div>

      <div className="profile-content">
        {/* Main Profile Card */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ delay: 0.2 }}
          className="main-profile-card"
        >
          <div className="profile-card-content">
            <div className="profile-layout">
              {/* Profile Image Section */}
              <div className="profile-image-section">
                <div className="image-container">
                  <img 
                    src={getProfileImage()} 
                    alt={providerData.name} 
                    className="profile-image"
                    onError={(e) => {
                      console.log('❌ Image failed to load:', e.target.src);
                      e.target.src = '/assets/default-profile.png';
                    }}
                  />
                  <div className="rating-badge">
                    ⭐ {averageRating}
                  </div>
                  <div className="provider-type-badge">
                    {providerData.providerType === 'verified' ? '✅ Verified' : '⭐ Professional'}
                  </div>
                </div>
                
                {/* Quick Actions */}
                <div className="quick-actions">
                  <button
                    onClick={handleAddToFavorites}
                    className="favorite-action-button"
                  >
                    ❤️ Favorite
                  </button>
                  <button
                    onClick={() => navigator.share?.({
                      title: providerData.name,
                      text: `Check out ${providerData.name} on SheWorks!`,
                      url: window.location.href
                    }).catch(console.error)}
                    className="share-action-button"
                  >
                    📤 Share
                  </button>
                </div>
              </div>

              {/* Provider Info */}
              <div className="provider-info-section">
                <div className="info-header">
                  <div className="header-main">
                    <h1 className="provider-name">
                      {providerData.name}
                    </h1>
                    <p className="provider-location">
                      📍 {providerData.location}
                    </p>
                    
                    {/* Rating and Reviews */}
                    <div className="provider-stats">
                      <div className="rating-stat">
                        <span className="stat-icon">⭐</span>
                        <span className="stat-value">{averageRating}</span>
                        <span className="stat-detail">({providerData.reviews} reviews)</span>
                      </div>
                      <div className="experience-stat">
                        <span className="stat-icon">⏱️</span>
                        <span className="stat-value">{providerData.experience}</span>
                      </div>
                      <div className="price-stat">
                        <span className="stat-icon">💰</span>
                        <span className="stat-value">{providerData.priceRange}</span>
                      </div>
                    </div>
                  </div>

                  {/* Main Action Buttons */}
                  <div className="action-buttons">
                    <motion.button 
                      className="book-service-button"
                      onClick={handleBooking}
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}
                    >
                      📅 Book Service
                    </motion.button>
                    <motion.button 
                      className="chat-button"
                      onClick={handleChat}
                      whileHover={{ scale: 1.05 }}
                      whileTap={{ scale: 0.95 }}
                    >
                      💬 Chat Now
                    </motion.button>
                  </div>
                </div>

                {/* Bio */}
                <p className="provider-bio">
                  {providerData.description || providerData.bio}
                </p>

                {/* Contact Information */}
                <div className="contact-info">
                  <div className="contact-item">
                    <span className="contact-icon">📞</span>
                    <div className="contact-details">
                      <p className="contact-label">Contact</p>
                      <p className="contact-value">{providerData.contact || providerData.phone}</p>
                    </div>
                  </div>
                  <div className="contact-item">
                    <span className="contact-icon">📧</span>
                    <div className="contact-details">
                      <p className="contact-label">Email</p>
                      <p className="contact-value">{providerData.email}</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </motion.div>

        {/* Tabs Navigation */}
        <div className="tabs-container">
          <div className="tabs-header">
            <nav className="tabs-navigation">
              {[
                { id: 'products', label: 'Products & Services', icon: '🛍️', count: providerData.products?.length || 0 },
                { id: 'reviews', label: 'Reviews', icon: '⭐', count: providerData.reviews || 0 },
                { id: 'about', label: 'About', icon: 'ℹ️' }
              ].map(tab => (
                <button
                  key={tab.id}
                  onClick={() => setActiveTab(tab.id)}
                  className={`tab-button ${activeTab === tab.id ? 'tab-active' : ''}`}
                >
                  <span className="tab-icon">{tab.icon}</span>
                  {tab.label}
                  {tab.count > 0 && (
                    <span className="tab-count">
                      {tab.count}
                    </span>
                  )}
                </button>
              ))}
            </nav>
          </div>

          {/* Tab Content */}
          <div className="tab-content">
            {/* Products Tab */}
            {activeTab === 'products' && (
              <ProductsTab 
                products={providerData.products || []} 
                onQuickBuy={handleQuickBuy}
                onAddToCart={handleAddToCart}
              />
            )}

            {/* Reviews Tab */}
            {activeTab === 'reviews' && (
              <ReviewsTab 
                averageRating={averageRating}
                reviewsCount={providerData.reviews || 0}
                onWriteReview={handleReview} 
                providerId={providerId}
              />
            )}

            {/* About Tab */}
            {activeTab === 'about' && (
              <AboutTab providerData={providerData} />
            )}
          </div>
        </div>
      </div>
    </motion.div>
  );
};

// Products Tab Component
const ProductsTab = ({ products, onQuickBuy, onAddToCart }) => {
  if (products.length === 0) {
    return (
      <div className="empty-state">
        <div className="empty-icon">🛍️</div>
        <h3 className="empty-title">No Products Available</h3>
        <p className="empty-description">This provider hasn't listed any products yet.</p>
      </div>
    );
  }

  return (
    <div className="products-tab">
      <div className="products-header">
        <h2 className="products-title">Available Products & Services</h2>
        <span className="products-count">{products.length} items</span>
      </div>
      
      <div className="products-grid">
        {products.map((product, index) => (
          <motion.div
            key={product.id}
            className="product-card"
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: index * 0.1 }}
            whileHover={{ y: -5 }}
          >
            {/* Product Image */}
            <div className="product-image-container">
              <img 
                src={product.image} 
                alt={product.name}
                className="product-image"
                onError={(e) => {
                  e.target.src = '/assets/default-product.jpg';
                }}
              />
              <div className="product-rating">
                ⭐ {product.rating}
              </div>
              {!product.inStock && (
                <div className="out-of-stock-overlay">
                  <span className="out-of-stock-label">
                    Out of Stock
                  </span>
                </div>
              )}
              {product.type === 'service' && (
                <div className="service-badge">
                  Service
                </div>
              )}
            </div>

            {/* Product Info */}
            <div className="product-info">
              <h3 className="product-name">
                {product.name}
              </h3>
              
              <p className="product-description">
                {product.description}
              </p>

              <div className="product-meta">
                <span className="product-price">
                  ₹{product.price}
                </span>
                <span className="product-reviews">
                  {product.reviews} reviews
                </span>
              </div>

              {/* Action Buttons */}
              <div className="product-actions">
                <button
                  onClick={() => onQuickBuy(product)}
                  disabled={!product.inStock}
                  className={`buy-button ${!product.inStock ? 'disabled' : ''}`}
                >
                  {product.type === 'service' ? 'Book Now' : product.inStock ? 'Buy Now' : 'Out of Stock'}
                </button>
                <button
                  onClick={(e) => onAddToCart(product, e)}
                  disabled={!product.inStock || product.type === 'service'}
                  className={`cart-button ${(!product.inStock || product.type === 'service') ? 'disabled' : ''}`}
                  title={product.type === 'service' ? 'Book Service' : product.inStock ? 'Add to cart' : 'Out of stock'}
                >
                  {product.type === 'service' ? '📅' : product.inStock ? '🛒' : '❌'}
                </button>
              </div>
            </div>
          </motion.div>
        ))}
      </div>
    </div>
  );
};

// Reviews Tab Component
const ReviewsTab = ({ averageRating, reviewsCount, onWriteReview, providerId }) => {
  // Get reviews from localStorage or generate sample ones
  const [reviews, setReviews] = useState([]);

  useEffect(() => {
    const storedReviews = JSON.parse(localStorage.getItem(`reviews_${providerId}`) || '[]');
    if (storedReviews.length > 0) {
      setReviews(storedReviews);
    } else {
      // Generate sample reviews if none exist
      const sampleReviews = Array.from({ length: Math.min(reviewsCount, 5) }, (_, index) => ({
        id: `review_${index}`,
        name: ['Priya Sharma', 'Ananya Patel', 'Divya Reddy', 'Sneha Kumar', 'Riya Gupta'][index],
        rating: Math.floor(Math.random() * 2) + 4, // 4-5 stars
        comment: `Excellent service! The quality was amazing and the attention to detail was impressive. Would definitely recommend!`,
        createdAt: new Date(Date.now() - Math.random() * 30 * 24 * 60 * 60 * 1000).toISOString()
      }));
      setReviews(sampleReviews);
    }
  }, [reviewsCount, providerId]);

  return (
    <div className="reviews-tab">
      <div className="reviews-header">
        <div className="reviews-info">
          <h2 className="reviews-title">Client Reviews & Ratings</h2>
          <p className="reviews-subtitle">What clients say about this provider</p>
        </div>
        
        <div className="reviews-stats">
          <div className="average-rating">
            <div className="rating-value">{averageRating}</div>
            <div className="rating-label">Average Rating</div>
          </div>
          <button
            onClick={onWriteReview}
            className="write-review-button"
          >
            ✍️ Write Review
          </button>
        </div>
      </div>

      {reviews.length === 0 ? (
        <div className="empty-state">
          <div className="empty-icon">⭐</div>
          <h3 className="empty-title">No Reviews Yet</h3>
          <p className="empty-description">Be the first to share your experience!</p>
          <button 
            onClick={onWriteReview}
            className="primary-button"
          >
            ✍️ Write First Review
          </button>
        </div>
      ) : (
        <div className="reviews-grid">
          {reviews.map((review, index) => (
            <motion.div
              key={review.id}
              className="review-card"
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: index * 0.1 }}
            >
              <div className="review-content">
                <div className="reviewer-avatar">
                  {review.name?.charAt(0) || 'A'}
                </div>
                <div className="review-details">
                  <div className="review-header">
                    <h4 className="reviewer-name">{review.name || 'Anonymous'}</h4>
                    <div className="review-rating">
                      {'★'.repeat(review.rating)}{'☆'.repeat(5 - review.rating)}
                    </div>
                  </div>
                  <p className="review-comment">{review.comment}</p>
                  <p className="review-date">
                    {review.createdAt ? new Date(review.createdAt).toLocaleDateString() : 'Recently'}
                  </p>
                </div>
              </div>
            </motion.div>
          ))}
        </div>
      )}
    </div>
  );
};

// About Tab Component
const AboutTab = ({ providerData }) => {
  const stats = [
    { label: 'Response Rate', value: providerData.responseRate || '95%', icon: '💬' },
    { label: 'Completion Rate', value: providerData.completionRate || '98%', icon: '✅' },
    { label: 'On Time Delivery', value: providerData.onTimeDelivery || '96%', icon: '⏱️' },
    { label: 'Customer Satisfaction', value: providerData.customerSatisfaction || '4.8/5', icon: '⭐' }
  ];

  return (
    <div className="about-tab">
      <h2 className="about-title">About {providerData.name}</h2>
      
      <div className="about-content">
        {/* Bio Section */}
        <div className="bio-section">
          <h3 className="section-title">Professional Bio</h3>
          <p className="bio-text">
            {providerData.bio || providerData.description || "No detailed bio provided yet."}
          </p>
        </div>

        {/* Stats Section */}
        <div className="stats-section">
          <h3 className="section-title">Performance Stats</h3>
          <div className="stats-grid">
            {stats.map((stat, index) => (
              <motion.div
                key={index}
                className="stat-card"
                initial={{ opacity: 0, scale: 0.9 }}
                animate={{ opacity: 1, scale: 1 }}
                transition={{ delay: index * 0.1 }}
              >
                <div className="stat-icon">{stat.icon}</div>
                <div className="stat-value">{stat.value}</div>
                <div className="stat-label">{stat.label}</div>
              </motion.div>
            ))}
          </div>
        </div>
      </div>

      {/* Additional Info */}
      <div className="additional-info">
        <InfoCard icon="📍" label="Location" value={providerData.location} />
        <InfoCard icon="⏱️" label="Experience" value={providerData.experience} />
        <InfoCard icon="📞" label="Contact" value={providerData.contact || providerData.phone} />
        <InfoCard icon="📧" label="Email" value={providerData.email} />
      </div>
    </div>
  );
};

// Info Card Component
const InfoCard = ({ icon, label, value }) => (
  <div className="info-card">
    <div className="info-content">
      <span className="info-icon">{icon}</span>
      <div className="info-details">
        <p className="info-label">{label}</p>
        <p className="info-value">{value}</p>
      </div>
    </div>
  </div>
);

export default ProviderProfileC;